server:
  port: 8080
spring:
  rabbitmq:
    host: localhost
    username: test
    password: test
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ftapp
    username: ftapp
    password: ftapp