server:
  port:8080
spring:
  rabbitmq:
    addresses: amqps://akbmsmvn:p7LrnyoGTK_pQ607Gj68T_Bu-VTCd8_B@toad.rmq.cloudamqp.com/akbmsmvn
    host: hawk.rmq.cloudamqp.com #toad.rmq.cloudamqp.com
    username: mhqvzuzz
    password: 6J3t9AcnZCUDByBEsx2hduU4dm-C395n
    port: 5672
    virtual-host: mhqvzuzz
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-80-122-11.compute-1.amazonaws.com:5432/d2duq9ekdqf40t
    username: njhcjjhszaojaq
    password: 66a1175a8f4e85e5a8f2e347a3f4596c52e8792920d9d986c43171f5aa0db70b
