server:
  ssl:
    key-store: C:/Users/User1337/springboot.p12 #classpath:keystore.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: springboot
    key-password: password
    port: 8443
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ftapp
    username: ftapp
    password: ftapp
#  security:
#    oauth2:
#      client:
#        registration:
#          client-id: fe0df921-754d-45e8-8d48-1fcef2d91df8
#          redirect-uri: https://ftapp.herokuapp.com/auth/hse_redirect
#          authorization-grant-type: authorization_code
#        provider:
#          authorization-uri: https://auth.hse.ru/adfs/oauth2/authorize
#          token-uri: https://auth.hse.ru/adfs/oauth2/token
